services:
  banco:
    image: postgres:16
    container_name: catalogo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: catalogo_plantas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  backend:
    image: bruna057/catalogo-de-planta-backend:latest
    container_name: catalogo-backend
    ports:
      - "3000:3000"
    depends_on:
      - banco
    environment:
      DB_HOST: banco
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: catalogo_plantas

  frontend:
    image: bruna057/catalogo-de-planta-frontend:latest
    container_name: catalogo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: